# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'millenia_ev.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_Millenia_eV(object):
    def setupUi(self, Millenia_eV):
        Millenia_eV.setObjectName(_fromUtf8("Millenia_eV"))
        Millenia_eV.resize(967, 561)
        self.centralWidget = QtWidgets.QWidget(Millenia_eV)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gB_Status = QtWidgets.QGroupBox(self.centralWidget)
        self.gB_Status.setGeometry(QtCore.QRect(10, 10, 411, 111))
        self.gB_Status.setObjectName(_fromUtf8("gB_Status"))
        self.label_status = QtWidgets.QLabel(self.gB_Status)
        self.label_status.setGeometry(QtCore.QRect(28, 47, 361, 31))
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName(_fromUtf8("label_status"))
        self.gB_Basic = QtWidgets.QGroupBox(self.centralWidget)
        self.gB_Basic.setGeometry(QtCore.QRect(10, 131, 411, 211))
        self.gB_Basic.setObjectName(_fromUtf8("gB_Basic"))
        self.frame = QtWidgets.QFrame(self.gB_Basic)
        self.frame.setGeometry(QtCore.QRect(9, 31, 171, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(118, 54, 41, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(118, 9, 41, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.vs_emission = QtWidgets.QSlider(self.frame)
        self.vs_emission.setGeometry(QtCore.QRect(70, 10, 41, 61))
        self.vs_emission.setMaximum(1)
        self.vs_emission.setOrientation(QtCore.Qt.Vertical)
        self.vs_emission.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.vs_emission.setTickInterval(1)
        self.vs_emission.setObjectName(_fromUtf8("vs_emission"))
        self.frame_2 = QtWidgets.QFrame(self.gB_Basic)
        self.frame_2.setGeometry(QtCore.QRect(200, 32, 181, 80))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(115, 55, 67, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(116, 10, 67, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(9, 30, 67, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.vs_shutter = QtWidgets.QSlider(self.frame_2)
        self.vs_shutter.setGeometry(QtCore.QRect(69, 10, 41, 61))
        self.vs_shutter.setMaximum(1)
        self.vs_shutter.setProperty("value", 0)
        self.vs_shutter.setSliderPosition(0)
        self.vs_shutter.setOrientation(QtCore.Qt.Vertical)
        self.vs_shutter.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.vs_shutter.setTickInterval(1)
        self.vs_shutter.setObjectName(_fromUtf8("vs_shutter"))
        self.frame_3 = QtWidgets.QFrame(self.gB_Basic)
        self.frame_3.setGeometry(QtCore.QRect(10, 120, 371, 80))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.lcd_power = QtWidgets.QLCDNumber(self.frame_3)
        self.lcd_power.setGeometry(QtCore.QRect(240, 16, 111, 51))
        self.lcd_power.setObjectName(_fromUtf8("lcd_power"))
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(18, 31, 31, 17))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(176, 21, 51, 41))
        self.label_10.setTextFormat(QtCore.Qt.RichText)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.sb_Power = QtWidgets.QDoubleSpinBox(self.frame_3)
        self.sb_Power.setGeometry(QtCore.QRect(60, 20, 61, 41))
        self.sb_Power.setDecimals(1)
        self.sb_Power.setMinimum(0.5)
        self.sb_Power.setMaximum(5.0)
        self.sb_Power.setSingleStep(0.1)
        self.sb_Power.setProperty("value", 0.5)
        self.sb_Power.setObjectName(_fromUtf8("sb_Power"))
        self.gB_Communications = QtWidgets.QGroupBox(self.centralWidget)
        self.gB_Communications.setGeometry(QtCore.QRect(450, 10, 501, 481))
        self.gB_Communications.setObjectName(_fromUtf8("gB_Communications"))
        self.tb_sent = QtWidgets.QTextEdit(self.gB_Communications)
        self.tb_sent.setGeometry(QtCore.QRect(30, 100, 200, 361))
        self.tb_sent.setReadOnly(True)
        self.tb_sent.setObjectName(_fromUtf8("tb_sent"))
        self.tb_recieved = QtWidgets.QTextEdit(self.gB_Communications)
        self.tb_recieved.setGeometry(QtCore.QRect(270, 100, 200, 361))
        self.tb_recieved.setReadOnly(True)
        self.tb_recieved.setObjectName(_fromUtf8("tb_recieved"))
        self.tb_send = QtWidgets.QLineEdit(self.gB_Communications)
        self.tb_send.setGeometry(QtCore.QRect(30, 50, 311, 25))
        self.tb_send.setObjectName(_fromUtf8("tb_send"))
        self.pb_send = QtWidgets.QPushButton(self.gB_Communications)
        self.pb_send.setGeometry(QtCore.QRect(360, 50, 89, 25))
        self.pb_send.setObjectName(_fromUtf8("pb_send"))
        self.label_11 = QtWidgets.QLabel(self.gB_Communications)
        self.label_11.setGeometry(QtCore.QRect(40, 80, 67, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtWidgets.QLabel(self.gB_Communications)
        self.label_12.setGeometry(QtCore.QRect(280, 80, 67, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gB_Alignment = QtWidgets.QGroupBox(self.centralWidget)
        self.gB_Alignment.setGeometry(QtCore.QRect(10, 349, 411, 141))
        self.gB_Alignment.setObjectName(_fromUtf8("gB_Alignment"))
        self.pb_alignment = QtWidgets.QPushButton(self.gB_Alignment)
        self.pb_alignment.setGeometry(QtCore.QRect(100, 30, 101, 41))
        self.pb_alignment.setObjectName(_fromUtf8("pb_alignment"))
        self.pb_powerMode = QtWidgets.QPushButton(self.gB_Alignment)
        self.pb_powerMode.setGeometry(QtCore.QRect(100, 90, 101, 41))
        self.pb_powerMode.setObjectName(_fromUtf8("pb_powerMode"))
        self.label_7 = QtWidgets.QLabel(self.gB_Alignment)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 41, 17))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtWidgets.QLabel(self.gB_Alignment)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 67, 17))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_mode = QtWidgets.QLabel(self.gB_Alignment)
        self.label_mode.setGeometry(QtCore.QRect(230, 66, 171, 31))
        self.label_mode.setObjectName(_fromUtf8("label_mode"))
        Millenia_eV.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(Millenia_eV)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 967, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        Millenia_eV.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(Millenia_eV)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        Millenia_eV.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(Millenia_eV)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        Millenia_eV.setStatusBar(self.statusBar)

        self.retranslateUi(Millenia_eV)
        QtCore.QMetaObject.connectSlotsByName(Millenia_eV)

    def retranslateUi(self, Millenia_eV):
        Millenia_eV.setWindowTitle(_translate("Millenia_eV", "Millenia_eV", None))
        self.gB_Status.setTitle(_translate("Millenia_eV", "Status", None))
        self.label_status.setText(_translate("Millenia_eV", "<html><head/><body><p><span style=\" font-size:20pt;\">Status</span></p></body></html>", None))
        self.gB_Basic.setTitle(_translate("Millenia_eV", "Laser Emission", None))
        self.label.setText(_translate("Millenia_eV", "Emission", None))
        self.label_4.setText(_translate("Millenia_eV", "Off", None))
        self.label_3.setText(_translate("Millenia_eV", "On", None))
        self.label_5.setText(_translate("Millenia_eV", "Closed", None))
        self.label_6.setText(_translate("Millenia_eV", "Open", None))
        self.label_2.setText(_translate("Millenia_eV", "Shutter", None))
        self.label_9.setText(_translate("Millenia_eV", "Set:", None))
        self.label_10.setText(_translate("Millenia_eV", "<html><head/><body><p>Power:</p></body></html>", None))
        self.gB_Communications.setTitle(_translate("Millenia_eV", "Communication", None))
        self.pb_send.setText(_translate("Millenia_eV", "Send", None))
        self.label_11.setText(_translate("Millenia_eV", "Sent", None))
        self.label_12.setText(_translate("Millenia_eV", "Recieved", None))
        self.gB_Alignment.setTitle(_translate("Millenia_eV", "Alignment Mode", None))
        self.pb_alignment.setText(_translate("Millenia_eV", "Alignment \n"
"Mode", None))
        self.pb_powerMode.setText(_translate("Millenia_eV", "Power \n"
"Mode", None))
        self.label_7.setText(_translate("Millenia_eV", "Begin", None))
        self.label_8.setText(_translate("Millenia_eV", "Normal", None))
        self.label_mode.setText(_translate("Millenia_eV", "<html><head/><body><p><span style=\" font-size:20pt;\">Power Mode</span></p><p><br/></p></body></html>", None))

